In [53]:
import sys
import os
from os import listdir
from os.path import join
import textgrids

path_ = '/media/erickgch/EGC/MT-FBK-internship/alignments/heroes_s2_10' #heroes_s2_3/segments_spa'

def get_phonemes(path):

    clues_es, clues_en = [], []
    for subdir, dirs, files in os.walk(path):
        for f in files:
            try:
                grid = textgrids.TextGrid(join(subdir, f))
            except TypeError:
                print('File ' + f + ' not in proper TextGrid format')
                pass
            temp_en = []
            temp_es = []
            for it in grid['MAU']:
                if '_spa_' in f:
                    temp_es.append((it.text, it.xmin, it.xmax))
                elif '_eng_' in f:
                    temp_en.append((it.text, it.xmin, it.xmax))
            if len(temp_es) > 0:
                clues_es.append(temp_es)
                temp_es, temp_en = [], []
            else:
                clues_en.append(temp_en)
                temp_en, temp_es = [], []
                
    return clues_en, clues_es

def get_labials(func):

    labials = ['b', 'v', 'f', 'w', 'B', 'F', 'p', 'm']
    exclusions = ['<p:>']

    lab_segs_eng, lab_segs_spa = [], []
    phr_count_eng, phr_count_spa = 0, 0

    for phr_en in func[0]:
        phr_count_eng += 1
        temp_ = []
        for i in phr_en:
            if set(labials).intersection(i[0]):
                if i[0] not in exclusions:
                    temp_.append(i)
            else:
                pass
        lab_segs_eng.append(('s2_10_seg'+str(phr_count_eng), temp_))
        temp_ = []

    for phr_es in func[1]:
        phr_count_spa += 1
        temp_ = []
        for k in phr_es:
            if set(labials).intersection(k[0]):
                if k[0] not in exclusions:
                    temp_.append(k)
            else:
                pass
        lab_segs_spa.append(('seg'+str(phr_count_spa), temp_))
        temp_ = []
        
    return lab_segs_eng, lab_segs_spa

labials_1 = get_labials(get_phonemes(path_))

import pandas as pd

my_df = pd.DataFrame({'ENG-SPA_id': [i[0] for i in labials_1[0]], 'Phonemes_ENG': [i[1] for i in labials_1[0]], 
                      'Phonemes_SPA': [i[1] for i in labials_1[1]]})
my_df['Total_phonemes_ENG'] = my_df['Phonemes_ENG'].apply(len)
my_df['Total_phonemes_SPA'] = my_df['Phonemes_SPA'].apply(len)

my_df

File heroes_s2_10_eng_aligned_eng0105.mau.TextGrid not in proper TextGrid format

,ENG-SPA_id,Phonemes_ENG,Phonemes_SPA,Total_phonemes_ENG,Total_phonemes_SPA
0,s2_10_seg1,"[(p, 0.0, 0.03), (v, 0.15, 0.19)]","[(p, 0.526, 0.566)]",2,1
1,s2_10_seg2,"[(w, 0.0, 0.03), (b, 0.29, 0.33), (w, 0.55, 0....","[(w, 0.046, 0.146), (B, 0.321, 0.406), (w, 0.4...",4,5
2,s2_10_seg3,"[(m, 0.45, 0.5), (v, 2.06, 2.09), (f, 2.32, 2....","[(b, 0.046, 0.096), (p, 0.916, 0.986), (p, 1.1...",3,4
3,s2_10_seg4,"[(v, 0.69, 0.76), (v, 0.83, 0.92)]","[(p, 0.486, 0.526), (b, 0.836, 0.876)]",2,2
4,s2_10_seg5,"[(m, 0.0, 0.15), (b, 0.22, 0.29)]","[(m, 0.0, 0.096)]",2,1
...,...,...,...,...,...
375,s2_10_seg376,"[(w, 0.0, 0.03)]",[],1,0
376,s2_10_seg377,"[(m, 0.22, 0.25), (m, 0.25, 0.3), (m, 0.91, 0....","[(m, 0.236, 0.366), (m, 0.666, 0.736), (m, 0.9...",7,7
377,s2_10_seg378,[],"[(p, 0.476, 0.506), (m, 0.596, 0.666)]",0,2
378,s2_10_seg379,"[(v, 0.31, 0.39)]","[(B, 0.476, 0.506), (B, 0.926, 0.976)]",1,2
379,s2_10_seg380,"[(m, 0.87, 0.92)]","[(m, 0.686, 0.776), (p, 0.776, 0.816)]",1,2

In [54]:
my_df.to_csv('labials_s2_10.csv')

In [55]:
df1 = pd.read_csv('labials_s2_1.csv')
df2 = pd.read_csv('labials_s2_6.csv')
df3 = pd.read_csv('labials_s2_10.csv')
df4 = pd.read_csv('labials_s3_2.csv')
df5 = pd.read_csv('labials_s3_8.csv')
df6 = pd.read_csv('labials_s3_9.csv')
df7 = pd.read_csv('labials_s3_11.csv')

In [61]:
new_df = df1.append(df2, ignore_index=True)
new_df = new_df.append(df3, ignore_index=True)
new_df = new_df.append(df4, ignore_index=True)
new_df = new_df.append(df5, ignore_index=True)
new_df = new_df.append(df6, ignore_index=True)
new_df = new_df.append(df7, ignore_index=True)

new_df

,Unnamed: 0,ENG-SPA_id,Phonemes_ENG,Phonemes_SPA,Total_phonemes_ENG,Total_phonemes_SPA
0,0,s2_1_seg1,[],"[('p', 2.246, 2.286), ('m', 2.926, 3.006), ('m...",0,6
1,1,s2_1_seg2,"[('f', 0.23, 0.35), ('v', 0.57, 0.62)]","[('p', 0.0, 0.026), ('m', 0.426, 0.486), ('m',...",2,3
2,2,s2_1_seg3,"[('w', 0.16, 0.21), ('p', 1.05, 1.1), ('b', 1....","[('w', 0.226, 0.336), ('p', 1.396, 1.426), ('B...",6,4
3,3,s2_1_seg4,"[('m', 0.33, 1.76), ('m', 2.0, 2.04), ('m', 3....","[('m', 0.616, 1.436), ('p', 1.586, 1.646), ('m...",9,10
4,4,s2_1_seg5,"[('f', 0.07, 0.1), ('v', 0.15, 0.18), ('f', 1....","[('B', 0.366, 0.416), ('m', 0.746, 0.816), ('p...",9,8
...,...,...,...,...,...,...
2342,118,s3_11_seg119,"[('w', 0.0, 0.03), ('b', 0.81, 0.88), ('f', 1....","[('B', 0.686, 0.716), ('B', 0.746, 0.776), ('w...",8,5
2343,119,s3_11_seg120,"[('b', 0.16, 0.19), ('v', 0.5, 0.55)]","[('m', 0.126, 0.156), ('p', 0.156, 0.186), ('B...",2,5
2344,120,s3_11_seg121,[],[],0,0
2345,121,s3_11_seg122,"[('b', 0.71, 0.74), ('w', 1.03, 1.06), ('b', 1...","[('m', 1.716, 1.766), ('b', 1.766, 1.796), ('m...",4,9
2346,122,s3_11_seg123,"[('w', 0.0, 0.04), ('w', 0.69, 0.72)]","[('B', 2.396, 2.436), ('p', 3.226, 3.256), ('p...",2,4

In [64]:
import scipy.stats as stats

stats.ttest_rel(my_df['Total_phonemes_ENG'], my_df['Total_phonemes_SPA'])

Ttest_relResult(statistic=2.673593841662696, pvalue=0.00782886333728065)